import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { Toaster } from 'sonner'
import { LayoutWrapper } from "@/components/layout-wrapper"
import { QueryProvider } from '@/providers/query-provider'

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Onion Coaching",
  description: "Generated by create next public",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} min-h-screen bg-gradient-to-b from-purple-50 via-white to-orange-50 
        antialiased selection:bg-[#E86C3A]/20 selection:text-[#E86C3A]`}
      >
        <QueryProvider>
          <LayoutWrapper>
            {children}
          </LayoutWrapper>
          <Toaster />
        </QueryProvider>
      </body>
    </html>
  );
}
